name: python workflow
on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: python python.py
jobs:
  build:
    runs-on: ubuntu-latest
    need: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: .
